version: '3'

services:
  gabs_mailer:
    build: .
    container_name: gabs_mailer
    restart: unless-stopped
    volumes:
      - ./config.json:/usr/app/build/config.json
networks:
  default:
    external:
      name: gabs_mailer_network