version: '3.1'

services:

  gabs_mailer_db:
    container_name: gabs_mailer_db
    build: .
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: gabs_mailer
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3336:3306
    volumes:
      - "./.mysql-data/_data:/var/lib/mysql"
    networks: 
      - gabs_mailer_network
  gabs_mailer_db_adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks: 
      - gabs_mailer_network

networks:
  gabs_mailer_network:
    driver: bridge
