version: '3.1'

services:

  gabs_mailer_db:
    container_name: gabs_mailer_db
    build: .
    command: --default-authentication-plugin=mysql_native_password --init-file=/usr/gabs_mailer/startup.sql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: gabs_mailer
      MYSQL_ROOT_PASSWORD: "9D2MyCHY9cXS7SKE"
    ports:
      - 3306:3306
    volumes:
      - "./.mysql-data/_data:/var/lib/mysql"
      - "./startup.sql:/usr/gabs_mailer/startup.sql"

networks:
  default:
    external:
      name: gabs_mailer_network
